# Generated by Django 4.2.23 on 2025-07-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encrypted_github_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
