# Generated by Django 4.2.23 on 2025-07-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0004_generateddocfolder_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(max_length=500)),
                ('owner', models.CharField(max_length=100)),
                ('repo_name', models.CharField(max_length=100)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('webhook_id', models.CharField(blank=True, max_length=100, null=True)),
                ('webhook_secret', models.CharField(default='<function uuid4 at 0x7f3579d89ca', max_length=100)),
                ('is_webhook_active', models.BooleanField(default=False)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('last_commit_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_failures', models.IntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_repo', to='dashboard.generateddocfolder')),
            ],
            options={
                'unique_together': {('owner', 'repo_name')},
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('push', 'Push'), ('ping', 'Ping'), ('pull_request', 'Pull Request'), ('other', 'Other')], max_length=20)),
                ('github_delivery_id', models.CharField(max_length=100, unique=True)),
                ('commit_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('files_processed', models.IntegerField(default=0)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('github_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='webhook.githubrepository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('action', models.CharField(max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_syncs', to='webhook.webhookevent')),
            ],
        ),
    ]
