# Generated by Django 4.2.23 on 2025-07-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='webhook_secret',
            field=models.CharField(default='<function uuid4 at 0x7ff6ced7cd3', max_length=100),
        ),
    ]
