# Generated by Django 4.2.23 on 2025-07-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_alter_githubrepository_webhook_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='webhook_secret',
            field=models.CharField(default='<function uuid4 at 0x7f5102bd2d3', max_length=100),
        ),
    ]
