# Generated by Django 4.2.23 on 2025-07-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_alter_githubrepository_webhook_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrepository',
            old_name='last_error_message',
            new_name='last_sync_error',
        ),
        migrations.AlterUniqueTogether(
            name='githubrepository',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='webhook_secret',
            field=models.CharField(default='<function uuid4 at 0x7fd362f0ddc', max_length=100),
        ),
    ]
