# Generated by Django 4.2.23 on 2025-07-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_rename_last_error_message_githubrepository_last_sync_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='webhook_secret',
            field=models.CharField(default='<function uuid4 at 0x7f9f13be8d3', max_length=100),
        ),
    ]
