# Generated by Django 4.2.23 on 2025-07-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('dashboard', '0002_generateddocfolder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocfolder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_folders', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='generateddocfolder',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('organization', 'Organization')], default='public', max_length=20),
        ),
    ]
