# Generated by Django 4.2.23 on 2025-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_generateddocfolder_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocfolder',
            name='source_type',
            field=models.CharField(choices=[('upload', 'Uploaded ZIP'), ('github', 'GitHub Repository')], default='upload', max_length=10),
        ),
    ]
