# Generated by Django 4.2.23 on 2025-07-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_generateddocfolder_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocfolder',
            name='auto_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generateddocfolder',
            name='github_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
